
export const usersList = [
  {
    key: '1',
    name: 'Sergio Jimenez Moreno',
    dni: '46274950R',
    address: 'New York No. 1 Lake Park',
    profile: ['JEFE_SALA'],
    webAccess: ['Con acceso'],
  },
  {
    key: '2',
    name: 'José Pérez Rodríguez',
    dni: '46274950R',
    address: 'London No. 1 Lake Park',
    profile: ['OPERARIO'],
    webAccess: ['Sin acceso'],
  },
  {
    key: '3',
    name: 'Jesús García López',
    dni: '46274950R',
    address: 'Sydney No. 1 Lake Park',
    profile: ['OPERARIO'],
    webAccess: ['Con acceso'],
  },
  {
    key: '4',
    name: 'Sergio Jimenez Moreno',
    dni: '46274950R',
    address: 'New York No. 1 Lake Park',
    profile: ['OPERARIO'],
    webAccess: ['Con acceso'],
  },
  {
    key: '5',
    name: 'José Pérez Rodríguez',
    dni: '46274950R',
    address: 'London No. 1 Lake Park',
    profile: ['OPERARIO'],
    webAccess: ['Sin acceso'],
  },
  {
    key: '6',
    name: 'Jesús García López',
    dni: '46274950R',
    address: 'Sydney No. 1 Lake Park',
    profile: ['ADMIN'],
    webAccess: ['Con acceso'],
  },
];